import { useState, useCallback } from 'react';
import { useAuth } from '@/context/AuthContext';

export interface Gym {
  _id: string;
  name: string;
  address: string;
  city: string;
  pincode: string;
  openTime: string;
  closeTime: string;
  facilities: string[];
  amenities: string[];
  phone: string;
  owner: {
    name: string;
    email: string;
    phone: string;
  };
  status: 'active' | 'inactive';
  approvedByAdmin: boolean;
}

// Lucknow gyms data
const mockGyms: Gym[] = [
  {
    _id: '1',
    name: 'Gold Gym Hazratganj',
    address: '12 Hazratganj, Near Sahara Ganj Mall',
    city: 'Lucknow',
    pincode: '226001',
    openTime: '05:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'CrossFit', 'Zumba'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'AC', 'Steam Room'],
    phone: '9889001234',
    owner: { name: 'Rajesh Tiwari', email: 'rajesh@goldgymlko.com', phone: '9889001234' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '2',
    name: 'Anytime Fitness Gomti Nagar',
    address: '45 Vibhuti Khand, Gomti Nagar',
    city: 'Lucknow',
    pincode: '226010',
    openTime: '00:00',
    closeTime: '23:59',
    facilities: ['Weights', 'Cardio', 'Personal Training', 'Functional'],
    amenities: ['24/7 Access', 'Locker Room', 'Shower', 'AC'],
    phone: '9889005678',
    owner: { name: 'Sanjay Mishra', email: 'sanjay@anytimefitness.com', phone: '9889005678' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '3',
    name: 'Fitness First Aliganj',
    address: '78 Sector C, Aliganj',
    city: 'Lucknow',
    pincode: '226024',
    openTime: '06:00',
    closeTime: '21:00',
    facilities: ['Weights', 'Yoga', 'Cardio', 'Dance'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'Juice Bar'],
    phone: '9889009012',
    owner: { name: 'Preeti Singh', email: 'preeti@fitnessfirst.com', phone: '9889009012' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '4',
    name: 'Muscle Factory Indira Nagar',
    address: '23 Faizabad Road, Indira Nagar',
    city: 'Lucknow',
    pincode: '226016',
    openTime: '05:30',
    closeTime: '22:30',
    facilities: ['Weights', 'Powerlifting', 'Cardio', 'Boxing'],
    amenities: ['Locker Room', 'Shower', 'Supplements Shop', 'AC'],
    phone: '9889003456',
    owner: { name: 'Vikas Yadav', email: 'vikas@musclefactory.com', phone: '9889003456' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '5',
    name: 'Wellness Hub Alambagh',
    address: '56 Kanpur Road, Alambagh',
    city: 'Lucknow',
    pincode: '226005',
    openTime: '06:00',
    closeTime: '22:00',
    facilities: ['Cardio', 'Yoga', 'Pilates', 'Swimming'],
    amenities: ['Pool', 'Locker Room', 'Shower', 'Cafe', 'AC'],
    phone: '9889007890',
    owner: { name: 'Meera Gupta', email: 'meera@wellnesshub.com', phone: '9889007890' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '6',
    name: 'FitZone Mahanagar',
    address: '34 Mahanagar Extension, Near PVR',
    city: 'Lucknow',
    pincode: '226006',
    openTime: '05:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'HIIT', 'Spinning'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'AC'],
    phone: '9889011111',
    owner: { name: 'Amit Srivastava', email: 'amit@fitzone.com', phone: '9889011111' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '7',
    name: 'Iron Temple Chinhat',
    address: '89 Chinhat Industrial Area',
    city: 'Lucknow',
    pincode: '226028',
    openTime: '05:00',
    closeTime: '23:00',
    facilities: ['Weights', 'Powerlifting', 'Strongman', 'Cardio'],
    amenities: ['Locker Room', 'Shower', 'Supplements Shop', 'Parking'],
    phone: '9889022222',
    owner: { name: 'Ravi Verma', email: 'ravi@irontemple.com', phone: '9889022222' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '8',
    name: 'CrossFit Lucknow',
    address: '12 Eldeco Udyan, Raebareli Road',
    city: 'Lucknow',
    pincode: '226025',
    openTime: '06:00',
    closeTime: '21:00',
    facilities: ['CrossFit', 'Functional', 'HIIT', 'Olympic Lifting'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'Cafe'],
    phone: '9889033333',
    owner: { name: 'Neeraj Pandey', email: 'neeraj@crossfitlko.com', phone: '9889033333' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '9',
    name: 'Yoga Shala Rajajipuram',
    address: '45 Sector H, Rajajipuram',
    city: 'Lucknow',
    pincode: '226017',
    openTime: '05:00',
    closeTime: '20:00',
    facilities: ['Yoga', 'Meditation', 'Pranayama', 'Pilates'],
    amenities: ['Locker Room', 'Shower', 'AC', 'Garden'],
    phone: '9889044444',
    owner: { name: 'Sunita Sharma', email: 'sunita@yogashala.com', phone: '9889044444' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '10',
    name: 'Power Gym Jankipuram',
    address: '78 Sector B, Jankipuram',
    city: 'Lucknow',
    pincode: '226021',
    openTime: '05:30',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'Boxing', 'MMA'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'AC'],
    phone: '9889055555',
    owner: { name: 'Deepak Singh', email: 'deepak@powergym.com', phone: '9889055555' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '11',
    name: 'Flex Fitness Ashiyana',
    address: '23 Ashiyana Colony, Near Metro Station',
    city: 'Lucknow',
    pincode: '226012',
    openTime: '06:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'Zumba', 'Aerobics'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'Cafe', 'AC'],
    phone: '9889066666',
    owner: { name: 'Pooja Agarwal', email: 'pooja@flexfitness.com', phone: '9889066666' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '12',
    name: 'Beast Mode Husainganj',
    address: '56 Husainganj, Near Charbagh',
    city: 'Lucknow',
    pincode: '226001',
    openTime: '05:00',
    closeTime: '23:00',
    facilities: ['Weights', 'Powerlifting', 'Cardio', 'Functional'],
    amenities: ['Locker Room', 'Shower', 'Steam Room', 'Sauna'],
    phone: '9889077777',
    owner: { name: 'Mohit Kapoor', email: 'mohit@beastmode.com', phone: '9889077777' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '13',
    name: 'Shree Gym Chowk',
    address: '89 Aminabad, Chowk',
    city: 'Lucknow',
    pincode: '226018',
    openTime: '06:00',
    closeTime: '21:00',
    facilities: ['Weights', 'Cardio', 'Yoga', 'Dance'],
    amenities: ['Locker Room', 'Shower', 'AC'],
    phone: '9889088888',
    owner: { name: 'Ram Prakash', email: 'ram@shreegym.com', phone: '9889088888' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '14',
    name: 'Elite Fitness Vikas Nagar',
    address: '12 Vikas Nagar, Near Fun Republic',
    city: 'Lucknow',
    pincode: '226022',
    openTime: '05:30',
    closeTime: '22:30',
    facilities: ['Weights', 'Cardio', 'CrossFit', 'Swimming'],
    amenities: ['Pool', 'Locker Room', 'Shower', 'Parking', 'AC'],
    phone: '9889099999',
    owner: { name: 'Ankit Rastogi', email: 'ankit@elitefitness.com', phone: '9889099999' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '15',
    name: 'Body Sculptors Aashiana',
    address: '34 Sector L, Aashiana',
    city: 'Lucknow',
    pincode: '226012',
    openTime: '06:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'Personal Training', 'Nutrition'],
    amenities: ['Locker Room', 'Shower', 'Supplements Shop', 'AC'],
    phone: '9889111111',
    owner: { name: 'Karan Mehta', email: 'karan@bodysculptors.com', phone: '9889111111' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '16',
    name: 'Transform Gym Sushant Golf City',
    address: '45 Sushant Golf City, Ansal API',
    city: 'Lucknow',
    pincode: '226030',
    openTime: '05:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'HIIT', 'Spinning'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'Cafe', 'AC'],
    phone: '9889122222',
    owner: { name: 'Gaurav Trivedi', email: 'gaurav@transformgym.com', phone: '9889122222' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '17',
    name: 'Spartan Fitness Kursi Road',
    address: '78 Kursi Road, Near Awadh Hospital',
    city: 'Lucknow',
    pincode: '226026',
    openTime: '05:30',
    closeTime: '22:30',
    facilities: ['Weights', 'Cardio', 'MMA', 'Boxing'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'AC'],
    phone: '9889133333',
    owner: { name: 'Harsh Dwivedi', email: 'harsh@spartanfitness.com', phone: '9889133333' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '18',
    name: 'Lakshya Gym Khurram Nagar',
    address: '23 Khurram Nagar, Near Lekhraj Metro',
    city: 'Lucknow',
    pincode: '226022',
    openTime: '06:00',
    closeTime: '21:00',
    facilities: ['Weights', 'Cardio', 'Yoga', 'Aerobics'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'AC'],
    phone: '9889144444',
    owner: { name: 'Vivek Bajpai', email: 'vivek@lakshyagym.com', phone: '9889144444' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '19',
    name: 'Fitness Hub Vinay Khand',
    address: '56 Vinay Khand, Gomti Nagar Extension',
    city: 'Lucknow',
    pincode: '226010',
    openTime: '05:00',
    closeTime: '23:00',
    facilities: ['Weights', 'Cardio', 'CrossFit', 'Zumba'],
    amenities: ['Locker Room', 'Shower', 'Steam Room', 'Parking', 'AC'],
    phone: '9889155555',
    owner: { name: 'Rohit Awasthi', email: 'rohit@fitnesshub.com', phone: '9889155555' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '20',
    name: 'Xtreme Fitness Sitapur Road',
    address: '89 Sitapur Road, Near Dubagga',
    city: 'Lucknow',
    pincode: '226020',
    openTime: '05:30',
    closeTime: '22:00',
    facilities: ['Weights', 'Powerlifting', 'Cardio', 'Functional'],
    amenities: ['Locker Room', 'Shower', 'Supplements Shop', 'Parking'],
    phone: '9889166666',
    owner: { name: 'Arun Shukla', email: 'arun@xtremefitness.com', phone: '9889166666' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '21',
    name: 'Sweat Factory Faizabad Road',
    address: '12 Faizabad Road, Near Polytechnic',
    city: 'Lucknow',
    pincode: '226016',
    openTime: '06:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'HIIT', 'Spinning'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'AC'],
    phone: '9889177777',
    owner: { name: 'Saurabh Tripathi', email: 'saurabh@sweatfactory.com', phone: '9889177777' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '22',
    name: 'Core Strength Indira Dam',
    address: '34 Indira Dam Road, Daliganj',
    city: 'Lucknow',
    pincode: '226020',
    openTime: '05:00',
    closeTime: '21:00',
    facilities: ['Weights', 'Cardio', 'Yoga', 'Pilates'],
    amenities: ['Locker Room', 'Shower', 'Garden', 'AC'],
    phone: '9889188888',
    owner: { name: 'Priya Tiwari', email: 'priya@corestrength.com', phone: '9889188888' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '23',
    name: 'Muscle Mantra IIM Road',
    address: '45 IIM Road, Near Prabhu Market',
    city: 'Lucknow',
    pincode: '226013',
    openTime: '05:30',
    closeTime: '22:30',
    facilities: ['Weights', 'Powerlifting', 'Cardio', 'Boxing'],
    amenities: ['Locker Room', 'Shower', 'Sauna', 'Parking', 'AC'],
    phone: '9889199999',
    owner: { name: 'Shivam Gupta', email: 'shivam@musclemantra.com', phone: '9889199999' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '24',
    name: 'Urban Gym Kaiserbagh',
    address: '78 Kaiserbagh, Near GPO',
    city: 'Lucknow',
    pincode: '226001',
    openTime: '06:00',
    closeTime: '22:00',
    facilities: ['Weights', 'Cardio', 'Zumba', 'Dance'],
    amenities: ['Locker Room', 'Shower', 'Juice Bar', 'AC'],
    phone: '9889211111',
    owner: { name: 'Neha Saxena', email: 'neha@urbangym.com', phone: '9889211111' },
    status: 'active',
    approvedByAdmin: true,
  },
  {
    _id: '25',
    name: 'Powerhouse Gym Telibagh',
    address: '23 Telibagh, Near Ring Road',
    city: 'Lucknow',
    pincode: '226029',
    openTime: '05:00',
    closeTime: '23:00',
    facilities: ['Weights', 'Cardio', 'CrossFit', 'Strongman'],
    amenities: ['Locker Room', 'Shower', 'Parking', 'Steam Room', 'AC'],
    phone: '9889222222',
    owner: { name: 'Vikrant Singh', email: 'vikrant@powerhousegym.com', phone: '9889222222' },
    status: 'active',
    approvedByAdmin: true,
  },
];

export const useGyms = () => {
  const { session } = useAuth();
  const [gyms, setGyms] = useState<Gym[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchGyms = useCallback(async (city?: string) => {
    setIsLoading(true);
    setError(null);
    
    // Using mock data for now - can be replaced with API call later
    const filteredGyms = city 
      ? mockGyms.filter(gym => gym.city.toLowerCase() === city.toLowerCase())
      : mockGyms;
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 300));
    
    setGyms(filteredGyms);
    setIsLoading(false);
  }, []);

  const getGymById = useCallback(async (id: string): Promise<Gym | null> => {
    // Using mock data
    return mockGyms.find(gym => gym._id === id) || null;
  }, []);

  return { gyms, isLoading, error, fetchGyms, getGymById };
};
